version: '3.8'
services:
  backend:
    build:
      context: ./
    ports:
      - "52560:5256"
    environment:
      - ASPNETCORE_URLS=http://+:5256
    depends_on:
      - postgres

  frontend:
    build:
      context: ../startup-front/
    ports:
      - "3000:80"
    container_name: react-container

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: myappdb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: